### PR TITLE
add github-ci and dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your project. I add github-actions and dependabot for github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Artem (@theavege),

While your approach works it has 2 caveats:
1. It only works for Linux runners
2. It uses the Ubuntu package for Lazarus and Free Pascal, and those are usually outdated

Please have a look at:
- https://github.com/gcarreno/setup-lazarus
- https://github.com/gcarreno/lazarus-with-github-actions

The first one is a GitHub action that installs newer versions of Lazarus/FPC ( and , yes, I've been lazy and haven't updated to 3.6 yet, sorry!! )
The second one is just a very simple example of how to use `setup-lazarus`.

Cheers,
Gus

**Comment by theavege** [comment]
// It uses the Ubuntu package for Lazarus and Free Pascal, and those are usually outdated
@gcarreno Thank you. What is missing in Ubuntu package for Lazarus and Free Pascal?
Have you submitted your project to [doublecmd](https://github.com/doublecmd/doublecmd), [zcad](https://github.com/zamtmn/zcad) and [CudaText](https://github.com/Alexey-T/CudaText)?

**Comment by gcarreno** [comment]
Hey Artem(@theavege),

> Thank you.

You're more than welcome!!

> What is missing in Ubuntu package for Lazarus and Free Pascal?

I don't think anything is missing. It's just that the Ubuntu team that do the packages are not that quick with picking up the latest stable. So they lag.

Apart from that, if you use `setup-lazarus`, you can compile natively on the GitHub runners for Windows and `macOS`.

With `setup-lazarus` you can also use the packages from `OPM`. It's a little buggy when you have a lot of dependencies, I'm aware that I need to fix that also.

> Have you submitted your project to [doublecmd](https://github.com/doublecmd/doublecmd), [zcad](https://github.com/zamtmn/zcad) and [CudaText](https://github.com/Alexey-T/CudaText)?

I'm not absolutely sure those 3 are aware of `setup-lazarus`, but I've noticed that Castle Game Engine is using it along with some other projects.

Cheers,
Gus

**Comment by theavege** [comment]
@gcarreno Could you make PR  with your solution CI in this project?

**Comment by gcarreno** [comment]
Hey Artem (@theavege),

Yeah, sure, I can do that.
Not right now, but I'll give it a go tomorrow or the next day.

Cheers,
Gus

**Comment by theavege** [comment]
@gcarreno Greate! Thank you! Could you make PR with your solution CI in [ConfigTD](https://github.com/PascalCorpsman/ConfigTD) also?

**Comment by gcarreno** [comment]
Hey Artem(@theavege),

For this repo: See https://github.com/wp-xyz/Hex/pull/6

For [ConfigTD](https://github.com/PascalCorpsman/ConfigTD) I'll need a bit more time to get my head around all the dependencies and how I can make that work.

Cheers,
Gus

**Comment by theavege** [comment]
@gcarreno Great job! Thanks!

**Comment by gcarreno** [comment]
Hey Artem(@theavege),

> Great job! Thanks!

No problem, you're more than welcome !!

Cheers,
Gus

**Pull request closed without merging**
